version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: estate_account_test
          POSTGRES_PASSWORD: ""
          POSTGRES_USER: postgres
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run:
                name: Database setup
                command: npx sequelize-cli db:create
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Test
          command: npm test
workflows:
    build-and-test:
      jobs:
        - build
        - test:
            requires:
              - build
