version: 2
jobs:
  build:
    working_directory: ~/estate-account
    parallelism: 1
    shell: /bin/bash --login
    # CircleCI 2.0 does not support environment variables that refer to each other the same way as 1.0 did.
    # If any of these refer to each other, rewrite them so that they don't or see https://circleci.com/docs/2.0/env-vars/#interpolating-environment-variables-to-set-other-environment-variables .
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/node:10.16.0
    - image: circleci/postgres:9.6-alpine
    steps:
    - checkout

    - run: export PATH="~/estate-account/node_modules/.bin:$PATH"
    - run: npm install
    # Save dependency cache
    - save_cache:
        key: v4-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ./node_modules
    # Test
    #   This would typically be a build job when using workflows, possibly combined with build
    # This is based on your 1.0 configuration file or project settings
    - run: npm run test:prepare
    - run: npm run test

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
